name: Python project continous integration (CI)

# trigger
# will run when event happens (e.g. push, pull request)
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to the runner (VM)
        uses: actions/checkout@v3 # predefined actions in Github

      - name: Setup python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.11

      - name: Install dependencies
        run: | # multiline commands
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 (code linter)
        run: flake8 --exclude=.venv .
        continue-on-error: true

      - name: Run black (code formatter)
        run: black .
